# Generated by Django 5.2.3 on 2025-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('device', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
