# Generated by Django 5.2.3 on 2025-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudml', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_fraud',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
